"use client";

import { useEffect, useState } from "react";
import type { AIStatus, KnowledgeSource } from "../types/ai";
import type { CustomerStatus } from "../types/customer";
import { SourceCard } from "./source-card";

type AICopilotPanelProps = { status: AIStatus; answer: string; errorMessage?: string; sources: KnowledgeSource[]; latencyMs: number; decomposed: boolean; isDemoMode: boolean; customerStatus: CustomerStatus; onAdopt: () => void; onSaveEdit: (value: string) => void; onRegenerate: () => void; onEscalate: () => void };
const statusCopy: Record<AIStatus, string> = { idle: "等待生成", loading: "生成中", success: "建议已生成", clarify: "需要补充信息", knowledge_insufficient: "知识依据不足", error: "服务异常" };

export function AICopilotPanel({ status, answer, errorMessage, sources, latencyMs, decomposed, isDemoMode, customerStatus, onAdopt, onSaveEdit, onRegenerate, onEscalate }: AICopilotPanelProps) {
  const [isEditing, setIsEditing] = useState(false); const [editValue, setEditValue] = useState(answer); const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  useEffect(() => { setIsEditing(false); setEditValue(answer); setIsDetailsOpen(false); }, [answer]);
  const isLoading = status === "loading"; const hasAnswer = status === "success" || status === "clarify" || status === "knowledge_insufficient"; const isInsufficient = status === "knowledge_insufficient";
  const sourceCountLabel = sources.length ? `${sources.length} 条` : isDemoMode ? "0 条" : "—";
  const visibleSources = sources.slice(0, 3);
  function saveEdit() { onSaveEdit(editValue.trim() || answer); setIsEditing(false); }
  const answerContent = isLoading ? "AI 正在整理建议回复…" : status === "error" ? errorMessage ?? "AI服务暂时不可用，请稍后重试。" : hasAnswer ? answer : "输入客户问题后，生成一条可供人工审核的建议回复。";
  return <aside className="panel copilot-panel"><header className="copilot-header"><div><p>AI Copilot</p><h2>建议回复</h2></div><span className={`copilot-state state-${status}`}>{statusCopy[status]}</span></header><div className={`ai-answer ${isInsufficient ? "answer-insufficient" : ""}`}><div className="answer-mark">AI</div>{isEditing ? <textarea className="answer-editor" aria-label="编辑 AI 建议回复" value={editValue} onChange={(event) => setEditValue(event.target.value)} rows={6} /> : <p className={isLoading ? "loading-copy" : undefined}>{answerContent}</p>}</div>{isInsufficient ? <p className="insufficient-notice">知识依据不足，建议人工确认</p> : null}{hasAnswer ? <><section className="sources-section"><div className="section-title"><h3>知识依据</h3><span>{sourceCountLabel}</span></div>{visibleSources.length ? visibleSources.map((source) => <SourceCard key={source.segmentId ?? `${source.title}-${source.tag}`} {...source} />) : <p className="empty-sources">{isDemoMode ? "当前结果没有可用知识依据。" : "当前 API 未返回可展示的引用信息"}</p>}</section><section className="processing-section"><button className="details-toggle" type="button" aria-expanded={isDetailsOpen} onClick={() => setIsDetailsOpen((value) => !value)}><span>查看处理详情</span><span className={`details-chevron ${isDetailsOpen ? "is-open" : ""}`}>⌄</span></button>{isDetailsOpen ? <div className="details-grid"><span>请求状态</span><strong>{statusCopy[status]}</strong><span>{isDemoMode ? "模拟响应耗时" : "响应耗时"}</span><strong>{`${latencyMs} ms`}</strong><span>引用知识数量</span><strong>{sourceCountLabel}</strong>{isDemoMode ? <><span>查询拆解</span><strong>{decomposed ? "已拆解" : "—"}</strong><span>人工审核状态</span><strong>{customerStatus}</strong></> : null}</div> : null}</section><div className="copilot-actions"><button className="primary-button full-button" type="button" onClick={onAdopt} disabled={isLoading}>采用建议</button><button className="secondary-button" type="button" onClick={() => setIsEditing(true)} disabled={isLoading}>编辑</button><button className="secondary-button" type="button" onClick={onRegenerate} disabled={isLoading}>重新生成</button><button className={`outline-button ${isInsufficient ? "human-review-button" : ""}`} type="button" onClick={onEscalate}>转人工</button>{isEditing ? <button className="secondary-button" type="button" onClick={saveEdit}>保存修改</button> : null}</div></> : null}</aside>;
}
